skript-links:
  any-version: "http://nfell2009.uk/skript/downloads/latest/Skript.jar"
  #version-specific:
    #1_8_X: "http://nfell2009.uk/skript/downloads/latest/Skript.jar"
scripts:
  #test:
    #hide: true
    #file-name: "test.sk"
addons:
  #skStuff:
    #any-version: "https://forums.skunity.com/uploads/default/original/2X/5/5c309250744ccc78f2e4673fb8291e39a3381adb.jar"